import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { Subject, debounceTime, distinctUntilChanged, switchMap } from 'rxjs';
import { AttributeDef, CustomTextFieldInput, ProductImageInput, SaveProductRequest, SaveVariantRequest, VariantOptionInput } from '../../../core/models/admin-catalog.model';
import { Brand, BundleComponent, Category, ProductCustomTextField, ProductDetail, ProductListItem, ProductVariant } from '../../../core/models/catalog.model';
import { AdminCatalogService } from '../../../core/services/admin-catalog.service';
import { CatalogService } from '../../../core/services/catalog.service';
import { MediaService } from '../../../core/services/media.service';
import { ProductSupplierInput, Supplier } from '../../../core/models/supplier.model';
import { SupplierService } from '../../../core/services/supplier.service';
import { AiAssistService } from '../../../core/services/ai-assist.service';
import { AiAssistButtonComponent } from '../../../shared/ai-assist/ai-assist-button.component';

/** A variant row generated by "Generate variants" that hasn't been saved (created) yet. */
interface PendingVariant {
  key: string;
  sku: string;
  name: string;
  priceAdjustment: number;
  isActive: boolean;
  options: VariantOptionInput[];
}

@Component({
  selector: 'app-admin-product-form',
  imports: [FormsModule, RouterLink, AiAssistButtonComponent],
  templateUrl: './admin-product-form.component.html',
})
export class AdminProductFormComponent implements OnInit {
  private readonly api = inject(AdminCatalogService);
  private readonly media = inject(MediaService);
  private readonly suppliers = inject(SupplierService);
  private readonly catalog = inject(CatalogService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  readonly ai = inject(AiAssistService);

  readonly seoBusy = signal(false);
  readonly seoError = signal<string | null>(null);

  readonly uploading = signal(false);

  readonly productId = signal<number | null>(null);
  readonly isEdit = computed(() => this.productId() !== null);
  readonly loading = signal(true);
  readonly saving = signal(false);
  readonly error = signal<string | null>(null);
  readonly message = signal<string | null>(null);

  readonly categories = signal<Category[]>([]);
  readonly brands = signal<Brand[]>([]);
  readonly attributeDefs = signal<AttributeDef[]>([]);
  readonly variants = signal<ProductVariant[]>([]);
  readonly pendingVariants = signal<PendingVariant[]>([]);
  optionRows: { name: string; valuesCsv: string }[] = [{ name: '', valuesCsv: '' }];

  readonly customTextFields = signal<ProductCustomTextField[]>([]);
  ctfRows: CustomTextFieldInput[] = [];

  readonly allSuppliers = signal<Supplier[]>([]);
  productSuppliers: ProductSupplierInput[] = [];

  readonly bundleItems = signal<BundleComponent[]>([]);
  readonly bundleResults = signal<ProductListItem[]>([]);
  readonly bundleError = signal<string | null>(null);
  readonly bundleSearch$ = new Subject<string>();
  bundleQuery = '';
  bundleQty = 1;
  pendingBundleProduct: number | null = null;
  pendingBundleName = '';

  form: SaveProductRequest = this.blank();
  newVariant: SaveVariantRequest = this.blankVariant();
  attrValues: Record<number, string> = {};

  constructor() {
    this.bundleSearch$.pipe(debounceTime(250), distinctUntilChanged(),
      switchMap((q) => this.catalog.getProducts({ search: q.trim(), pageSize: 8 })))
      .subscribe((r) => this.bundleResults.set(r.items.filter((p) => p.productId !== this.productId())));
  }

  ngOnInit(): void {
    this.ai.ensureStatus();
    this.api.listCategories().subscribe((c) => this.categories.set(c));
    this.api.listBrands().subscribe((b) => this.brands.set(b));
    this.api.listAttributes().subscribe((a) => this.attributeDefs.set(a));

    this.suppliers.list().subscribe((s) => this.allSuppliers.set(s));

    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.productId.set(+id);
      this.loadProduct(+id);
      this.loadProductSuppliers(+id);
      this.loadBundleItems(+id);
      this.loadCustomTextFields(+id);
    } else {
      this.loading.set(false);
    }
  }

  private blank(): SaveProductRequest {
    return {
      sku: '', name: '', categoryId: 0, brandId: null, price: 0, compareAtPrice: null, costPrice: null,
      shortDescription: '', description: '', hsnCode: '', status: 'Active', isFeatured: false,
      productType: '', tags: '', metaTitle: '', metaDescription: '', images: [], isBundle: false,
      excludeFromRecommendations: false, pinnedInRecommendations: false,
    };
  }

  private blankVariant(): SaveVariantRequest {
    return { sku: '', name: '', priceAdjustment: 0, isActive: true, options: [] };
  }

  private loadProduct(id: number): void {
    this.loading.set(true);
    this.api.getProduct(id).subscribe({
      next: (p: ProductDetail) => {
        this.form = {
          sku: p.sku, name: p.name, categoryId: p.categoryId, brandId: p.brandId,
          price: p.price, compareAtPrice: p.compareAtPrice, costPrice: p.costPrice,
          shortDescription: p.shortDescription, description: p.description, hsnCode: p.hsnCode,
          status: p.status, isFeatured: p.isFeatured,
          productType: p.productType, tags: p.tags, metaTitle: p.metaTitle, metaDescription: p.metaDescription,
          images: p.images.map((i) => ({ url: i.url, altText: i.altText, displayOrder: i.displayOrder, isPrimary: i.isPrimary })),
          isBundle: p.isBundle,
          excludeFromRecommendations: p.excludeFromRecommendations ?? false,
          pinnedInRecommendations: p.pinnedInRecommendations ?? false,
        };
        this.variants.set(p.variants);
        this.attrValues = {};
        for (const a of p.attributes) this.attrValues[a.attributeId] = a.value ?? a.valueText ?? '';
        this.loading.set(false);
      },
      error: () => { this.error.set('Could not load product.'); this.loading.set(false); },
    });
  }

  // --- Images ---
  addImage(): void {
    this.form.images!.push({ url: '', altText: '', displayOrder: this.form.images!.length, isPrimary: this.form.images!.length === 0 });
  }
  removeImage(i: number): void {
    this.form.images!.splice(i, 1);
  }
  setPrimary(i: number): void {
    this.form.images!.forEach((img, idx) => (img.isPrimary = idx === i));
  }
  uploadImage(img: ProductImageInput, event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) return;
    this.uploading.set(true);
    this.error.set(null);
    this.media.upload(file).subscribe({
      next: (m) => { img.url = m.url; img.mediaFileId = m.mediaFileId; this.uploading.set(false); },
      error: () => { this.uploading.set(false); this.error.set('Image upload failed (max 5 MB; JPG/PNG/WebP/GIF only).'); },
    });
    input.value = '';
  }

  // --- Save product ---
  saveProduct(): void {
    if (!this.form.sku.trim() || !this.form.name.trim()) { this.error.set('SKU and Name are required.'); return; }
    if (!this.form.categoryId) { this.error.set('Please choose a category.'); return; }
    this.saving.set(true);
    this.error.set(null);
    this.message.set(null);

    const op = this.isEdit() ? this.api.updateProduct(this.productId()!, this.form) : this.api.createProduct(this.form);
    op.subscribe({
      next: (p) => {
        this.saving.set(false);
        this.message.set('Saved.');
        if (!this.isEdit()) this.router.navigate(['/admin/products', p.productId]);
      },
      error: (e) => { this.saving.set(false); this.error.set(e?.error?.message ?? 'Save failed.'); },
    });
  }

  // --- SEO (✨ generate meta title + description) ---
  generateSeo(): void {
    if (!this.form.name.trim()) { this.seoError.set('Add a product name first.'); return; }
    this.seoBusy.set(true); this.seoError.set(null);
    this.ai.seo(this.form.name, this.form.description || undefined).subscribe({
      next: (s) => { this.form.metaTitle = s.title; this.form.metaDescription = s.metaDescription; this.seoBusy.set(false); },
      error: (e: unknown) => {
        this.seoBusy.set(false);
        const err = e as { status?: number; error?: { message?: string } };
        this.seoError.set(err?.status === 402
          ? (err.error?.message ?? 'Out of AI credits.')
          : (err?.error?.message ?? 'Could not generate SEO. Please try again.'));
      },
    });
  }

  // --- Variants: manual single-variant add (kept for a one-off variant without using the generator) ---
  addVariantOption(): void {
    this.newVariant.options!.push({ optionName: '', optionValue: '' });
  }
  addVariant(): void {
    if (!this.productId() || !this.newVariant.sku.trim()) return;
    this.api.createVariant(this.productId()!, this.newVariant).subscribe({
      next: () => { this.newVariant = this.blankVariant(); this.reloadVariants(); },
      error: (e) => this.error.set(e?.error?.message ?? 'Variant failed.'),
    });
  }
  saveVariant(v: ProductVariant): void {
    if (!v.sku.trim()) { this.error.set('Variant SKU is required.'); return; }
    this.api.updateVariant(this.productId()!, v.productVariantId, { sku: v.sku, name: v.name, priceAdjustment: v.priceAdjustment, isActive: v.isActive, options: v.options }).subscribe({
      next: () => this.flash('Variant saved.'),
      error: (e) => this.error.set(e?.error?.message ?? 'Save failed.'),
    });
  }
  deleteVariant(v: ProductVariant): void {
    this.api.deleteVariant(this.productId()!, v.productVariantId).subscribe({
      next: () => this.reloadVariants(),
      error: (e) => this.error.set(e?.error?.message ?? 'Delete failed.'),
    });
  }
  private reloadVariants(): void {
    this.api.listVariants(this.productId()!).subscribe((v) => this.variants.set(v));
  }
  variantLabel(v: ProductVariant): string {
    return v.options.length ? v.options.map((o) => `${o.optionName}: ${o.optionValue}`).join(', ') : v.sku;
  }

  // --- Product options & variants: define Option: Values pairs, generate the full combination matrix ---
  addOptionRow(): void { this.optionRows.push({ name: '', valuesCsv: '' }); }
  removeOptionRow(i: number): void { this.optionRows.splice(i, 1); }

  generateVariants(): void {
    const options = this.optionRows
      .map((o) => ({ name: o.name.trim(), values: o.valuesCsv.split(',').map((v) => v.trim()).filter((v) => v.length > 0) }))
      .filter((o) => o.name.length > 0 && o.values.length > 0);
    if (!options.length) return;

    let combos: VariantOptionInput[][] = [[]];
    for (const opt of options) {
      const next: VariantOptionInput[][] = [];
      for (const combo of combos) for (const value of opt.values) next.push([...combo, { optionName: opt.name, optionValue: value }]);
      combos = next;
    }

    const usedSkus = new Set([...this.variants().map((v) => v.sku), ...this.pendingVariants().map((v) => v.sku)]);
    const baseSku = (this.form.sku || 'SKU').trim().toUpperCase().replace(/\s+/g, '-');
    const rows: PendingVariant[] = combos.map((combo) => {
      const suffix = combo.map((c) => this.skuPart(c.optionValue)).join('-');
      let sku = `${baseSku}-${suffix}`;
      let n = 2;
      while (usedSkus.has(sku)) sku = `${baseSku}-${suffix}-${n++}`;
      usedSkus.add(sku);
      return { key: sku, sku, name: combo.map((c) => c.optionValue).join(' / '), priceAdjustment: 0, isActive: true, options: combo };
    });
    this.pendingVariants.set(rows);
  }

  private skuPart(value: string): string {
    return value.trim().toUpperCase().replace(/[^A-Z0-9]+/g, '');
  }

  savePendingVariant(row: PendingVariant): void {
    if (!row.sku.trim()) { this.error.set('Variant SKU is required.'); return; }
    this.api.createVariant(this.productId()!, { sku: row.sku, name: row.name, priceAdjustment: row.priceAdjustment, isActive: row.isActive, options: row.options }).subscribe({
      next: () => { this.pendingVariants.set(this.pendingVariants().filter((r) => r.key !== row.key)); this.reloadVariants(); },
      error: (e) => this.error.set(e?.error?.message ?? 'Variant failed.'),
    });
  }
  removePendingVariant(row: PendingVariant): void {
    this.pendingVariants.set(this.pendingVariants().filter((r) => r.key !== row.key));
  }

  // --- Custom text (personalization) fields ---
  private loadCustomTextFields(id: number): void {
    this.api.getCustomTextFields(id).subscribe((f) => {
      this.customTextFields.set(f);
      this.ctfRows = f.length ? f.map((x) => ({ label: x.label, maxLength: x.maxLength, isMandatory: x.isMandatory })) : [this.blankCtfRow()];
    });
  }
  private blankCtfRow(): CustomTextFieldInput { return { label: '', maxLength: 255, isMandatory: false }; }
  addCtfRow(): void { this.ctfRows.push(this.blankCtfRow()); }
  removeCtfRow(i: number): void { this.ctfRows.splice(i, 1); }
  saveCustomTextFields(): void {
    const fields = this.ctfRows.filter((r) => r.label.trim().length > 0);
    this.api.setCustomTextFields(this.productId()!, { fields }).subscribe({
      next: (f) => {
        this.customTextFields.set(f);
        this.ctfRows = f.length ? f.map((x) => ({ label: x.label, maxLength: x.maxLength, isMandatory: x.isMandatory })) : [this.blankCtfRow()];
        this.flash('Custom text fields saved.');
      },
      error: (e) => this.error.set(e?.error?.message ?? 'Failed.'),
    });
  }

  private flash(m: string): void { this.message.set(m); setTimeout(() => this.message.set(null), 3000); }

  // --- Bundle contents ---
  private loadBundleItems(id: number): void {
    this.api.getBundleItems(id).subscribe((items) => this.bundleItems.set(items));
  }
  pickBundleItem(id: number, name: string): void {
    this.pendingBundleProduct = id;
    this.pendingBundleName = name;
    this.bundleQuery = name;
    this.bundleResults.set([]);
  }
  addBundleItem(): void {
    if (!this.productId() || !this.pendingBundleProduct) return;
    const items = [
      ...this.bundleItems().map((c) => ({ componentProductId: c.componentProductId, componentVariantId: c.componentVariantId, quantity: c.quantity })),
      { componentProductId: this.pendingBundleProduct, componentVariantId: null, quantity: Math.max(1, this.bundleQty) },
    ];
    this.bundleError.set(null);
    this.api.saveBundleItems(this.productId()!, items).subscribe({
      next: (r) => { this.bundleItems.set(r); this.pendingBundleProduct = null; this.bundleQuery = ''; this.bundleQty = 1; },
      error: (e) => this.bundleError.set(e?.error?.message ?? 'Could not add item.'),
    });
  }
  removeBundleItem(c: BundleComponent): void {
    const items = this.bundleItems()
      .filter((x) => x.componentProductId !== c.componentProductId || x.componentVariantId !== c.componentVariantId)
      .map((x) => ({ componentProductId: x.componentProductId, componentVariantId: x.componentVariantId, quantity: x.quantity }));
    this.api.saveBundleItems(this.productId()!, items).subscribe({
      next: (r) => this.bundleItems.set(r),
      error: (e) => this.bundleError.set(e?.error?.message ?? 'Could not remove item.'),
    });
  }

  // --- Attributes ---
  saveAttributes(): void {
    const inputs = this.attributeDefs()
      .filter((a) => (this.attrValues[a.attributeId] ?? '').trim().length > 0)
      .map((a) => ({ attributeId: a.attributeId, valueText: this.attrValues[a.attributeId].trim() }));
    this.api.setProductAttributes(this.productId()!, inputs).subscribe({
      next: () => this.message.set('Specifications saved.'),
      error: (e) => this.error.set(e?.error?.message ?? 'Failed.'),
    });
  }

  // --- Suppliers ---
  private loadProductSuppliers(id: number): void {
    this.suppliers.forProduct(id).subscribe((ps) => {
      this.productSuppliers = ps.map((p) => ({
        supplierId: p.supplierId, supplierSku: p.supplierSku, costPrice: p.costPrice,
        leadTimeDays: p.leadTimeDays, isPrimary: p.isPrimary,
      }));
    });
  }
  addProductSupplier(): void {
    this.productSuppliers.push({
      supplierId: 0, supplierSku: null, costPrice: null, leadTimeDays: null,
      isPrimary: this.productSuppliers.length === 0,
    });
  }
  removeProductSupplier(i: number): void {
    this.productSuppliers.splice(i, 1);
  }
  setPrimarySupplier(i: number): void {
    this.productSuppliers.forEach((ps, idx) => (ps.isPrimary = idx === i));
  }
  saveProductSuppliers(): void {
    const rows = this.productSuppliers.filter((ps) => ps.supplierId);
    if (rows.length && !rows.some((ps) => ps.isPrimary)) rows[0].isPrimary = true;
    this.suppliers.setForProduct(this.productId()!, rows).subscribe({
      next: () => this.message.set('Suppliers saved.'),
      error: (e) => this.error.set(e?.error?.message ?? 'Failed.'),
    });
  }
}
