import { Routes } from '@angular/router';
import { adminGuard, authGuard, superAdminGuard } from './core/guards/auth.guard';
import { homeResolver } from './features/home/home.resolver';

export const routes: Routes = [
  {
    path: '',
    resolve: { home: homeResolver },
    loadComponent: () => import('./features/home/home.component').then((m) => m.HomeComponent),
  },
  {
    path: 'products',
    loadComponent: () => import('./features/storefront/collection/collection-page.component').then((m) => m.CollectionPageComponent),
  },
  {
    path: 'category/:slug',
    loadComponent: () => import('./features/storefront/collection/collection-page.component').then((m) => m.CollectionPageComponent),
  },
  {
    path: 'product/:slug',
    loadComponent: () => import('./features/storefront/product/product-page.component').then((m) => m.ProductPageComponent),
  },
  {
    path: 'cart',
    loadComponent: () => import('./features/storefront/cart/cart-page.component').then((m) => m.CartPageComponent),
  },
  {
    path: 'checkout',
    canActivate: [authGuard],
    loadComponent: () => import('./features/checkout/checkout.component').then((m) => m.CheckoutComponent),
  },
  {
    path: 'account',
    canActivate: [authGuard],
    loadComponent: () => import('./features/account/account-layout.component').then((m) => m.AccountLayoutComponent),
    children: [
      { path: '', redirectTo: 'profile', pathMatch: 'full' },
      { path: 'profile', loadComponent: () => import('./features/account/profile.component').then((m) => m.ProfileComponent) },
      { path: 'addresses', loadComponent: () => import('./features/account/addresses.component').then((m) => m.AddressesComponent) },
      { path: 'orders', loadComponent: () => import('./features/orders/order-history.component').then((m) => m.OrderHistoryComponent) },
      { path: 'orders/:id', loadComponent: () => import('./features/orders/order-detail.component').then((m) => m.OrderDetailComponent) },
      { path: 'wishlist', loadComponent: () => import('./features/account/wishlist.component').then((m) => m.WishlistComponent) },
      { path: 'notifications', loadComponent: () => import('./features/notifications/notifications-page.component').then((m) => m.NotificationsPageComponent) },
    ],
  },
  { path: 'signup', loadComponent: () => import('./features/onboarding/signup.component').then((m) => m.SignupComponent) },
  { path: 'password', loadComponent: () => import('./features/pages/password/store-password.component').then((m) => m.StorePasswordComponent) },
  { path: 'superadmin', canActivate: [superAdminGuard], loadComponent: () => import('./features/superadmin/superadmin-dashboard.component').then((m) => m.SuperAdminDashboardComponent) },
  { path: 'collection/:slug', loadComponent: () => import('./features/catalog/collection/collection.component').then((m) => m.CollectionComponent) },
  { path: 'policies/:handle', loadComponent: () => import('./features/pages/policy/policy.component').then((m) => m.PolicyComponent) },
  { path: 'pages/:slug', loadComponent: () => import('./features/pages/page.component').then((m) => m.PageComponent) },
  { path: 'about', loadComponent: () => import('./features/pages/about/about.component').then((m) => m.AboutComponent) },
  { path: 'contact', loadComponent: () => import('./features/pages/contact/contact.component').then((m) => m.ContactComponent) },
  { path: 'faq', loadComponent: () => import('./features/pages/faq/faq.component').then((m) => m.FaqComponent) },
  {
    path: 'login',
    loadComponent: () => import('./features/auth/login/login.component').then((m) => m.LoginComponent),
  },
  {
    path: 'forgot-password',
    loadComponent: () => import('./features/auth/forgot-password/forgot-password.component').then((m) => m.ForgotPasswordComponent),
  },
  {
    path: 'register',
    loadComponent: () => import('./features/auth/register/register.component').then((m) => m.RegisterComponent),
  },
  { path: 'admin/pages/:id/build', canActivate: [adminGuard], loadComponent: () => import('./features/admin/builder/admin-builder.component').then((m) => m.AdminBuilderComponent) },
  { path: 'admin/theme-editor/:themeId', canActivate: [adminGuard], loadComponent: () => import('./features/admin/theme-editor/admin-theme-editor.component').then((m) => m.AdminThemeEditorComponent) },
  {
    path: 'admin',
    canActivate: [adminGuard],
    loadComponent: () => import('./features/admin/admin-layout.component').then((m) => m.AdminLayoutComponent),
    children: [
      { path: '', loadComponent: () => import('./features/admin/home/admin-home.component').then((m) => m.AdminHomeComponent) },
      { path: 'products', loadComponent: () => import('./features/admin/catalog/admin-products.component').then((m) => m.AdminProductsComponent) },
      { path: 'products/new', loadComponent: () => import('./features/admin/catalog/admin-product-form.component').then((m) => m.AdminProductFormComponent) },
      { path: 'products/:id', loadComponent: () => import('./features/admin/catalog/admin-product-form.component').then((m) => m.AdminProductFormComponent) },
      { path: 'categories', loadComponent: () => import('./features/admin/catalog/admin-categories.component').then((m) => m.AdminCategoriesComponent) },
      { path: 'collections', loadComponent: () => import('./features/admin/collections/admin-collections.component').then((m) => m.AdminCollectionsComponent) },
      { path: 'collections/new', loadComponent: () => import('./features/admin/collections/admin-collection-edit.component').then((m) => m.AdminCollectionEditComponent) },
      { path: 'collections/:id', loadComponent: () => import('./features/admin/collections/admin-collection-edit.component').then((m) => m.AdminCollectionEditComponent) },
      { path: 'brands', loadComponent: () => import('./features/admin/catalog/admin-brands.component').then((m) => m.AdminBrandsComponent) },
      { path: 'attributes', loadComponent: () => import('./features/admin/catalog/admin-attributes.component').then((m) => m.AdminAttributesComponent) },
      { path: 'inventory', loadComponent: () => import('./features/admin/inventory/admin-inventory.component').then((m) => m.AdminInventoryComponent) },
      { path: 'orders', loadComponent: () => import('./features/admin/orders/admin-orders.component').then((m) => m.AdminOrdersComponent) },
      { path: 'draft-orders', loadComponent: () => import('./features/admin/orders/admin-draft-orders.component').then((m) => m.AdminDraftOrdersComponent) },
      { path: 'draft-orders/new', loadComponent: () => import('./features/admin/orders/admin-draft-order-new.component').then((m) => m.AdminDraftOrderNewComponent) },
      { path: 'draft-orders/:id', loadComponent: () => import('./features/admin/orders/admin-draft-order-detail.component').then((m) => m.AdminDraftOrderDetailComponent) },
      { path: 'reviews', loadComponent: () => import('./features/admin/reviews/admin-reviews.component').then((m) => m.AdminReviewsComponent) },
      { path: 'coupons', loadComponent: () => import('./features/admin/coupons/admin-coupons.component').then((m) => m.AdminCouponsComponent) },
      { path: 'analytics', loadComponent: () => import('./features/admin/analytics/admin-analytics.component').then((m) => m.AdminAnalyticsComponent) },
      { path: 'suppliers', loadComponent: () => import('./features/admin/suppliers/admin-suppliers.component').then((m) => m.AdminSuppliersComponent) },
      { path: 'customers', loadComponent: () => import('./features/admin/customers/admin-customers.component').then((m) => m.AdminCustomersComponent) },
      { path: 'customers/new', loadComponent: () => import('./features/admin/customers/admin-customer-new.component').then((m) => m.AdminCustomerNewComponent) },
      { path: 'customers/:id', loadComponent: () => import('./features/admin/customers/admin-customer-detail.component').then((m) => m.AdminCustomerDetailComponent) },
      { path: 'notifications', loadComponent: () => import('./features/notifications/notifications-page.component').then((m) => m.NotificationsPageComponent) },
      { path: 'store-settings', loadComponent: () => import('./features/admin/settings/admin-store-settings.component').then((m) => m.AdminStoreSettingsComponent) },
      { path: 'staff', loadComponent: () => import('./features/admin/staff/admin-staff.component').then((m) => m.AdminStaffComponent) },
      { path: 'billing', loadComponent: () => import('./features/admin/billing/admin-billing.component').then((m) => m.AdminBillingComponent) },
      { path: 'policies', loadComponent: () => import('./features/admin/settings/admin-policies.component').then((m) => m.AdminPoliciesComponent) },
      { path: 'preferences', loadComponent: () => import('./features/admin/settings/admin-preferences.component').then((m) => m.AdminPreferencesComponent) },
      { path: 'checkout-settings', loadComponent: () => import('./features/admin/settings/admin-checkout-settings.component').then((m) => m.AdminCheckoutSettingsComponent) },
      { path: 'notification-templates', loadComponent: () => import('./features/admin/settings/admin-notification-templates.component').then((m) => m.AdminNotificationTemplatesComponent) },
      { path: 'domain', loadComponent: () => import('./features/admin/settings/admin-domain.component').then((m) => m.AdminDomainComponent) },
      { path: 'payments', loadComponent: () => import('./features/admin/settings/admin-payments.component').then((m) => m.AdminPaymentsComponent) },
      { path: 'shipping', loadComponent: () => import('./features/admin/settings/admin-shipping.component').then((m) => m.AdminShippingComponent) },
      { path: 'theme', loadComponent: () => import('./features/admin/theme/admin-theme.component').then((m) => m.AdminThemeComponent) },
      { path: 'themes', loadComponent: () => import('./features/admin/theme-editor/admin-theme-library.component').then((m) => m.AdminThemeLibraryComponent) },
      { path: 'pages', loadComponent: () => import('./features/admin/builder/admin-pages.component').then((m) => m.AdminPagesComponent) },
      { path: 'navigation', loadComponent: () => import('./features/admin/navigation/admin-navigation.component').then((m) => m.AdminNavigationComponent) },
      { path: 'files', loadComponent: () => import('./features/admin/files/admin-files.component').then((m) => m.AdminFilesComponent) },
      { path: 'home-page', loadComponent: () => import('./features/admin/cms/admin-cms.component').then((m) => m.AdminCmsComponent) },
      { path: 'banners', loadComponent: () => import('./features/admin/cms/admin-banners.component').then((m) => m.AdminBannersComponent) },
      { path: 'import', loadComponent: () => import('./features/admin/catalog/admin-import.component').then((m) => m.AdminImportComponent) },
      { path: 'auth-providers', loadComponent: () => import('./features/admin/auth-providers/auth-providers.component').then((m) => m.AuthProvidersComponent) },
    ],
  },
  { path: '**', redirectTo: '' },
];
